pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'us-east-2' // Change to your desired region
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/wasimamshaikh/terra-multistage.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('dev') {
                    sh 'terraform init'
                }
            }
        }
    }
}